### PR TITLE
Update xo_install.sh

### PR DESCRIPTION
**Pull request by mallouris**
installing and using  yarn package manager. Modify the creation the systemd  xo-server.service.

### CODE REVIEW

**Comment by Jarli01** [comment]
Hi Mallouris, 

All development has been moved to https://github.com/Jarli01/xenorchestra_installer which already contains many of these required changes.

**Comment by mallouris** [comment]
Ok. thanks for letting me know.

**Comment by Jarli01** [comment]
If you'd like I can add you as a contributor to that ongoing project. 

Let me know

**Comment by mallouris** [comment]
Yes that would be nice. I might contribute some more. Do you have in mind the autoXOA (https://github.com/hackmods/autoXOA), i was wondering may be we could go to that direction? what do you think

**Comment by Jarli01** [comment]
It adds complexity without any real reason. The solution in place now installed to Debian / ubuntu and there is no need for the GUI. Also using the XOA name isn't fair, as it clearly is not XOA. XOA is the paid supported appliance from olivier and his team.

**Comment by mallouris** [comment]
I agree the XOA name is misguiding users and developers. May be XOC (Xen Orchestra Community) would be more appropriate.

**Pull request closed without merging**
